### ISSUE TITLE
Exclude conda-tree from depends output

### ISSUE THREAD

**Issue by captaincoordinates** [conda-incubator/conda-tree#17]
Thanks for the really helpful tool!

Could we please have the option to exclude the `conda-tree` dependency chain from `deptree` and other commands?

**Comment by rvalieris** [comment]
hello, 

yes, having an way to exclude undesired results from deptree sounds like a good idea, I will look into that.

**Comment by rvalieris** [comment]
Added a --exclude option to remove some packages from the tree.

also I documented the usage of conda-tree as a conda sub-command check it out, that way you don't need to install conda-tree on every env.
