### ISSUE TITLE
Invitation to join the `conda-incubator` organization

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-tree#20]
Hi @rvalieris 

I have been using conda-tree lately to debug some issues in my environments and it has been incredibly useful. Thanks for the work put into this!

I would like to mention the possibility of transferring this project into the official `conda-incubator` organization, home to many community-driven conda projects. You would retain full rights to the repository, of course! 

If you are interested, let me know!

Thanks,
Jaime.

**Comment by jaimergp** [comment]
Awesome! I have invited you to the organization. Once accepted, you can initiate the transfer. Feel free to [join us on Slack](https://join.slack.com/t/conda/shared_invite/zt-1gbwyn1nk-rfDNaR8wFkAq4s812Rs0tg) too if you want!

**Comment by rvalieris** [comment]
done !

**Comment by jaimergp** [comment]
Excellent! I have restored your access rights too. Let me know if there's anything missing!
