### ISSUE TITLE
Print json instead of python repr

### ISSUE THREAD

**Issue by indigoviolet** [conda-incubator/conda-tree#21]
Thank you for this tool, it is super helpful. 

The output of `conda tree leaves` looks like JSON, but is actually a stringified version of a Python list, and annoying to parse. I suggest either adding a `--json` option or even better just printing valid JSON.

**Comment by rvalieris** [comment]
yes, thats a good point. the print(list) is something I added very early on but haven't changed since but it should have been something simpler like one package per line. we could also add --json option too.

**Comment by rvalieris** [comment]
new version now prints one package per line, and a --json option prints proper json.
