### ISSUE TITLE
troubleshooting constraint on updating a package

### ISSUE THREAD

**Issue by rootsmusic** [conda-incubator/conda-tree#23]
I tried to update [numexpr](https://anaconda.org/conda-forge/numexpr), but it says "All requested packages already installed".  `whoneeds` doesn't list anything, but `depends` lists a few packages including python.  How can I identify which is the constraint on updating?  Thanks.

**Comment by rvalieris** [comment]
Hello,

to force a package to update try this:
`conda install numexpr>=X.Y`

where X.Y is the minimum version you want installed
