### ISSUE TITLE
including build with namespace

### ISSUE THREAD

**Issue by rootsmusic** [conda-incubator/conda-tree#25]
My environment has two versions of the same package, with the only difference being their channel.  I want to investigate why the same package was installed redundantly.  However, `conda tree` doesn't recognize the build when I include it with the namespace.  I've tried the following:
- importlib_metadata=6.7.0=hd8ed1ab_0
- importlib_metadata-6.7.0-hd8ed1ab_0
- importlib_metadata-6.7.0-hd8ed1ab_0.conda
- importlib_metadata=6.7.0=hd8ed1ab_0.conda

**Comment by rootsmusic** [comment]
> I'm not sure about this, but I think installing two packages with the same name shouldn't be possible, conda should be replacing one for the other.

@rvalieris I thought that conda shouldn't install duplicates too, until I discovered the following builds in my environment.  So I'd like conda-tree to investigate whether one of these builds can be removed without breaking other packages.
> # Name                      Version                            Build     Channel
> importlib-metadata        6.7.0              pyha770c72_0    intel
> importlib_metadata        6.7.0                  hd8ed1ab_0    conda-forge

**Comment by rvalieris** [comment]
ahh, I just noticed these two package aren't actually duplicates, one uses a dash `-`, the other uses underline `_`

I'm not sure why in your case they are coming from different channels but you can check which package depends on those with these commands:

```bash
$ conda tree whoneeds -r -t importlib-metadata

$ conda tree whoneeds -r -t importlib_metadata
```

**Comment by rootsmusic** [comment]
Sorry, my eyesight overlooked it.
